### ISSUE TITLE
保存用户名密码功能

### ISSUE THREAD

**Issue by jingsenzhu** [Mythologyli/ZJU-Connect-for-Windows#2]
可否增加记住登录信息的选项，每次启动不需要重新输入

**Comment by Mythologyli** [comment]
密码目前故意设置为不记忆，用户名应该是能记住的。你实测可以记忆用户名吗？

**Comment by jingsenzhu** [comment]
> 密码目前故意设置为不记忆，用户名应该是能记住的。你实测可以记忆用户名吗？

我这边实测是用户名也记不住。另外是否记住密码的问题，可以加个勾选框作为选项呗？

**Comment by Mythologyli** [comment]
请检查：

`C:\Users\用户名\AppData\Local\ZJU Connect for Windows` 下有没有 `config.ini` 文件。如果有，将文件内容中可能存在的账号、密码信息用 xxxxxx 代替后粘贴上来

记住密码功能移除主要是配置文件保存位置单一，密码明文储存安全性较低。关于这个功能我再考虑一下

**Comment by jingsenzhu** [comment]
> 请检查：
> 
> `C:\Users\用户名\AppData\Local\ZJU Connect for Windows` 下有没有 `config.ini` 文件。如果有，将文件内容中可能存在的账号、密码信息用 xxxxxx 代替后粘贴上来
> 
> 记住密码功能移除主要是配置文件保存位置单一，密码明文储存安全性较低。关于这个功能我再考虑一下

找到了，我刚才记不住用户名是因为没有完全退出上一个打开的后台（我以为把窗口叉掉就退出了，没注意到有后台），彻底退出后重新打开是能够记住用户名的

关于密码存储的问题，如果不麻烦的话可以用些简单的加密算法储存密文？

**Comment by CS123n** [comment]
> 请检查：
> 
> `C:\Users\用户名\AppData\Local\ZJU Connect for Windows` 下有没有 `config.ini` 文件。如果有，将文件内容中可能存在的账号、密码信息用 xxxxxx 代替后粘贴上来
> 
> 记住密码功能移除主要是配置文件保存位置单一，密码明文储存安全性较低。关于这个功能我再考虑一下

可以加一个简单的编解码（base64?）再存储到config.ini。譬如密码abc，编码成xxx存入config.ini，加载时解码回abc。

**Comment by windingwind** [comment]
> 可以加一个简单的编解码（base64?）
b64编码可逆就基本没有啥防护作用

可以让用户自己选择记录一个密码文件保存路径之类的，每次开起来都要手输密码挺麻烦的

**Comment by Mythologyli** [comment]
已完成密码保存功能，预计今晚发布新版本
