### ISSUE TITLE
正版软件管理与服务平台无法使用

### ISSUE THREAD

**Issue by YXTR** [Mythologyli/ZJU-Connect-for-Windows#3]
在使用 EasyConnect 的时候，可以正常使用“正版软件管理与服务平台”来利用学校提供的激活服务激活Windows和Office，在使用ZJU-Connect的情况下，这个激活软件无法正常使用（表现为无法登录并自动退出）。请问是否有方法可以使得该软件可以正常工作？

**Comment by Mythologyli** [comment]
可以参考 98 帖子配合 Clash + ZJU Rule 使用，然后开启 Clash 的 TUN 模式
建议到 [TG 群](https://t.me/zjuers)内讨论
